name: Build the flutter version of the RustDesk

on:
  workflow_dispatch:

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VCPKG_ROOT: 'C:\vcpkg'
  # تنظیم مسیرها برای شناسایی توسط کامپایلر
  INCLUDE: 'C:\vcpkg\installed\x64-windows-static\include'
  LIB: 'C:\vcpkg\installed\x64-windows-static\lib'

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-for-windows:
    name: Windows-Build-Standard-Success
    needs: [generate-bridge]
    runs-on: windows-2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install NASM (Required)
        uses: ilammy/setup-nasm@v1

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.SCITER_RUST_VERSION }}
          targets: x86_64-pc-windows-msvc

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ env.VCPKG_ROOT }}
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Install Minimal Essential Dependencies
        shell: pwsh
        run: |
          # ما فقط پکیج های سبک و حیاتی را نصب می کنیم تا رم پر نشود
          & "${{ env.VCPKG_ROOT }}\vcpkg.exe" install opus:x64-windows-static libvpx:x64-windows-static libyuv:x64-windows-static --x-install-root="${{ env.VCPKG_ROOT }}\installed"

      - name: Build rustdesk
        shell: pwsh
        env:
          INCLUDE: 'C:\vcpkg\installed\x64-windows-static\include'
          LIB: 'C:\vcpkg\installed\x64-windows-static\lib'
          VCPKG_ROOT: 'C:\vcpkg'
        run: |
          # بیلد بدون hwcodec برای جلوگیری از خطای ffmpeg و aom
          python3 .\build.py --flutter --skip-portable-pack
          
          if (Test-Path "./flutter/build/windows/x64/runner/Release") {
            mv ./flutter/build/windows/x64/runner/Release ./rustdesk-output
          } else {
            Write-Error "Build failed!"
            exit 1
          }

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: RustDesk-Windows-Standard
          path: rustdesk-output/
