name: Build the flutter version of the RustDesk

on:
  workflow_dispatch:

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.5"
  VCPKG_ROOT: 'C:\vcpkg'
  SIGN_BASE_URL: "-2"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-for-windows:
    name: Windows-Build-Success-Final
    needs: [generate-bridge]
    runs-on: windows-2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install NASM (Required for AOM)
        uses: ilammy/setup-nasm@v1

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Restore bridge files
        uses: actions/download-artifact@v4
        with:
          name: bridge-artifact
          path: ./

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.SCITER_RUST_VERSION }}
          targets: x86_64-pc-windows-msvc
          components: rustfmt

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ env.VCPKG_ROOT }}
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Install vcpkg dependencies
        shell: pwsh
        run: |
          # محدود کردن پردازش برای جلوگیری از کراش رم
          $env:VCPKG_MAX_CONCURRENCY = "2"
          
          # نصب کتابخانه‌ها با استفاده از پورت‌های پروژه
          & "${{ env.VCPKG_ROOT }}\vcpkg.exe" install `
            --triplet x64-windows-static `
            --x-install-root="${{ env.VCPKG_ROOT }}\installed" `
            --overlay-ports="${{ github.workspace }}\res\vcpkg" `
            --clean-after-build

      - name: Build rustdesk
        shell: pwsh
        env:
          # استفاده از تک کوتیشن برای مسیرهای ویندوزی جهت جلوگیری از خطای YAML
          INCLUDE: 'C:\vcpkg\installed\x64-windows-static\include'
          LIB: 'C:\vcpkg\installed\x64-windows-static\lib'
          VCPKG_ROOT: 'C:\vcpkg'
        run: |
          python3 .\build.py --flutter --hwcodec --skip-portable-pack
          
          if (Test-Path "./flutter/build/windows/x64/runner/Release") {
            mv ./flutter/build/windows/x64/runner/Release ./rustdesk-output
          } else {
            Write-Error "Build failed! Output directory not found."
            exit 1
          }

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: RustDesk-Windows-Success
          path: rustdesk-output/
